name: Secure PR merge with build check
permissions:
  contents: write
  pull-requests: write
on:
  pull_request: 
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  check-override:
    runs-on: ubuntu-latest
    outputs:
      allow-merge: ${{ steps.check-override.outputs.allow-merge }}
    steps:
      - name: Check for override comment
        id: check-override
        run: |
          allow_merge=false
          authorized_users=("AjaySusanth")
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" == "/override" ]]; then
              is_pr_comment="${{ github.event.issue.pull_request != null }}"
              commenter=${{ github.event.comment.user.login }}

              if [[ "$is_pr_comment" == "true" ]]; then
                for user in "${authorized_users[@]}"; do
                  if [[ "$commenter" == "$user" ]]; then
                    allow_merge=true
                    break
                  fi
                done
              fi
            fi
          fi
          echo "allow-merge=$allow_merge" >> $GITHUB_OUTPUT
        

  build-check:
    needs: check-override
    if: needs.check-override.outputs.allow-merge == 'false'
    runs-on: ubuntu-latest
    defaults:
            run:
                working-directory: demo-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
  approve-merge:
    needs: [check-override, build-check]
    runs-on: ubuntu-latest
    outputs:
          merge: ${{ steps.approve-merge.outputs.merge }}
    if: always()
    steps:
      - name: Check PR for merge
        id: approve-merge
        run: |
          echo "Allow merge: ${{ needs.check-override.outputs.allow-merge }}"
          echo "Build check: ${{ needs.build-check.result || 'skipped' }}"
          if [[ "${{ needs.check-override.outputs.allow-merge }}" == "true" ]] || [[ "${{ needs.build-check.result || 'skipped' }}" == "success" ]]; then
             echo "merge=true" >> $GITHUB_OUTPUT
            echo "PR approved for merge"
          else 
            echo "merge=false" >> $GITHUB_OUTPUT
            echo "PR not approved for merge"
            exit 1
          fi
  merge-pr:
    needs: approve-merge
    if: always()  # Change to always() to force running condition checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Check why merge is skipped
        if: ${{ !(success() && needs.approve-merge.outputs.merge == 'true') }}
        run: |
          echo "Skipped because:"
          echo "approve-merge success: ${{ needs.approve-merge.result == 'success' }}"
          echo "merge-approved: ${{ needs.approve-merge.outputs.merge }}"
          exit 1
          

      - name: Set PR number or URL
        id: pr_info
        run: |
          if [[ -z "${{ github.event.pull_request.html_url }}" ]]; then
            echo "No PR URL found. Using PR number instead."
            echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          else
            echo "Valid PR URL found: ${{ github.event.pull_request.html_url }}"
            echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          fi

      - name: Merge PR by number or URL
        run: |
          if [[ -n "$PR_URL" ]]; then
            echo "Merging PR with URL: $PR_URL"
            curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -d '{"commit_title": "Merge PR #${{ env.PR_NUMBER }}", "merge_method": "merge", "bypass_pull_request_reviews": true}' \
            "$PR_URL/merge"
          else
            echo "Merging PR #${PR_NUMBER}..."
            curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -d '{"commit_title": "Merge PR #${{ env.PR_NUMBER }}", "merge_method": "merge", "bypass_pull_request_reviews": true}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          PR_URL: ${{ env.PR_URL }}
