name: Secure PR merge with buiild check
on:
  pull_request: 
    branches: [main]

jobs:
  check-label:
    runs-on: ubuntu-latest
    outputs:
      allow-merge: ${{steps.check-label.outputs.allow-merge}}
    steps:
      - name: Check for override label
        id: check-label
        run: |
          if [[ "${{github.event.pull_request.labels.*.name}}" == *'override'*]]; then
            echo "allow-merge=true" >> $GITHUB_OUTPUT
          else
            echo "allow-merge=false" >> $GITHUB_OUTPUT
  build-check:
    needs: check-label
    if: needs.check-label.outputs.allow-merge == 'false'
    runs-on: ubuntu-latest
    defaults:
            run:
                working-directory: demo-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
  approve-merge:
    needs: [check-label, build-check]
    runs-on: ubuntu-latest
    if: always() && needs.check-label.outputs.allow-merge == 'true' || needs.build-check.result == 'success'
    steps:
      - name: Approve PR for merge
        run: echo "PR is approved for merge"