name: Secure PR merge with build check
on:
  pull_request: 
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  check-override:
    runs-on: ubuntu-latest
    outputs:
      allow-merge: ${{steps.check-override.outputs.allow-merge}}
    steps:
      - name: Check for override comment
        id: check-override
        run: |
          allow_merge=false
          authorized_users=("AjaySusanth")
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            if [[ "${{ github.event.comment.body }}" == "/override" ]]; then
              is_pr_comment="${{ github.event.issue.pull_request != null }}"
              commenter=${{ github.event.comment.user.login }}

              if [[ "$is_pr_comment" == "true" ]]; then
                for user in "${authorized_users[@]}"; do
                  if [[ "$commenter" == "$user" ]]; then
                    allow_merge=true
                    break
                  fi
                done
              fi
            fi
          fi
          echo "allow-merge=$allow_merge" >> $GITHUB_OUTPUT
        

  build-check:
    needs: check-override
    if: needs.check-override.outputs.allow-merge == 'false'
    runs-on: ubuntu-latest
    defaults:
            run:
                working-directory: demo-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
  approve-merge:
    needs: [check-override, build-check]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check PR for merge
        run: |
          echo "Allow merge: ${{ needs.check-override.outputs.allow-merge }}"
          echo "Build check: ${{ needs.build-check.result || 'skipped' }}"
          if [[ "${{ needs.check-override.outputs.allow-merge }}" == "true" ]] || [[ "${{ needs.build-check.result || 'skipped' }}" == "success" ]]; then
            echo "PR approved for merge"
            exit 0
          else 
            echo "PR not approved for merge"
            exit 1
          fi
      - name: Merge pr
        if: success()
        run: |
          echo "Merging PR..."
          gh pr merge "$PR_URL" --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }} 
